[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = false

[client]
showErrorDetails = "none"
toolbarMode = "auto"
showSidebarNavigation = true

[logger]
level = "info"
messageFormat = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

[runner]
magicEnabled = false
fastReruns = true
enforceSerializableSessionState = false
enumCoercion = "nameOnly"

[server]

# List of folders that should not be watched for changes.
# Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
# Default: []
folderWatchBlacklist = []
fileWatcherType = "poll"

# Symmetric key used to produce signed cookies. If deploying on multiple
# replicas, this should be set to the same value across all replicas to ensure
# they all share the same secret.
# Default: randomly generated secret key.
# cookieSecret = "a-random-key-appears-here"

# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or
# (2) we are running in the Streamlit Atom plugin.
headless = false

runOnSave = false

# The address where the server will listen for client and browser
# connections. Use this if you want to bind the server to a specific address.
# If set, the server will only be accessible from this address, and not from
# any aliases (like localhost).
# Default: (unset)
# address =

port = 8501

# The base path for the URL where Streamlit should be served from.
# Default: ""
# baseUrlPath = ""

enableCORS = true
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
# maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
# maxMessageSize = 200

# Enables support for websocket compression.
# Default: false
# enableWebsocketCompression = false

# Enable serving files from a `static` directory in the running app's
# directory.
# Default: false
# enableStaticServing = false

# TTL in seconds for sessions whose websockets have been disconnected. The server
# may choose to clean up session state, uploaded files, etc for a given session
# with no active websocket connection at any point after this time has passed.
# Default: 120
disconnectedSessionTTL = 120

[browser]

# Internet address where users should point their browsers in order to
# connect to the app. Can be IP address or DNS name and path.
# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Default: "localhost"
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false

# Port where users should point their browsers in order to connect to the
# app.
# This is used to:
# - Set the correct URL for XSRF protection purposes.
# - Show the URL on the terminal (part of `streamlit run`).
# - Open the browser automatically (part of `streamlit run`).
# This option is for advanced use cases. To change the port of your app, use
# `server.Port` instead. Don't use port 3000 which is reserved for internal
# development.
# Default: whatever value is set in server.port.
serverPort = 8501

[secrets]

# List of locations where secrets are searched. An entry can be a path to a
# TOML file or directory path where Kubernetes style secrets are saved.
# Order is important, import is first to last, so secrets in later files
# will take precedence over earlier ones.
# Default: [ <path to local environment's secrets.toml file>, <path to project's secrets.toml file>,]
# files = [ "~/.streamlit/secrets.toml", "~/project directory/.streamlit/secrets.toml",]